global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "litellm"
    authorization:
      credentials: admin
    static_configs:
      - targets: ["litellm:4000"]
    metrics_path: /metrics