/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/knowledge/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_admin_v1_knowledge_documents_get"];
        put?: never;
        /** Ingest Document */
        post: operations["ingest_document_admin_v1_knowledge_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/knowledge/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_admin_v1_knowledge_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/knowledge/documents/{doc_id}/subject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Document Subject */
        put: operations["set_document_subject_admin_v1_knowledge_documents__doc_id__subject_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/knowledge/documents/{doc_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Document Tags */
        patch: operations["edit_document_tags_admin_v1_knowledge_documents__doc_id__tags_patch"];
        trace?: never;
    };
    "/admin/v1/knowledge/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_admin_v1_knowledge_documents__doc_id__get"];
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_admin_v1_knowledge_documents__doc_id__delete"];
        options?: never;
        head?: never;
        /** Rename Document */
        patch: operations["rename_document_admin_v1_knowledge_documents__doc_id__patch"];
        trace?: never;
    };
    "/admin/v1/knowledge/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subjects */
        get: operations["list_subjects_admin_v1_knowledge_subjects_get"];
        put?: never;
        /** Create Subject */
        post: operations["create_subject_admin_v1_knowledge_subjects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/knowledge/subjects/{subject_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Subject */
        delete: operations["delete_subject_admin_v1_knowledge_subjects__subject_id__delete"];
        options?: never;
        head?: never;
        /** Edit Subject */
        patch: operations["edit_subject_admin_v1_knowledge_subjects__subject_id__patch"];
        trace?: never;
    };
    "/admin/v1/memory/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_admin_v1_memory_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/memory/users/{user_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_admin_v1_memory_users__user_id__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/memory/users/{user_id}/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Fact */
        post: operations["add_fact_admin_v1_memory_users__user_id__facts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/memory/users/{user_id}/facts/{fact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Fact */
        delete: operations["delete_fact_admin_v1_memory_users__user_id__facts__fact_id__delete"];
        options?: never;
        head?: never;
        /** Update Fact */
        patch: operations["update_fact_admin_v1_memory_users__user_id__facts__fact_id__patch"];
        trace?: never;
    };
    "/admin/v1/memory/users/{user_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List User Sessions */
        get: operations["list_user_sessions_admin_v1_memory_users__user_id__sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/memory/users/{user_id}/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_admin_v1_memory_users__user_id__sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/memory/persona": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Persona */
        get: operations["get_persona_admin_v1_memory_persona_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/memory/files/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Raw File */
        get: operations["get_raw_file_admin_v1_memory_files__kind__get"];
        /** Put Raw File */
        put: operations["put_raw_file_admin_v1_memory_files__kind__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddFact */
        AddFact: {
            /**
             * Text
             * @description The fact to add.
             */
            text: string;
            /**
             * Expected Version
             * @description The version from the last read; rejected with 409 if stale.
             */
            expected_version?: string | null;
        };
        /** ChunkOut */
        ChunkOut: {
            /** Chunk Index */
            chunk_index: number;
            /** Text */
            text: string;
        };
        /** CreateSubject */
        CreateSubject: {
            /**
             * Name
             * @description The subject name (unique, case-insensitive).
             */
            name: string;
            /**
             * Description
             * @description Optional description.
             * @default
             */
            description: string;
        };
        /**
         * DocumentDetailOut
         * @description A single document: doc-level fields + its chunks in order.
         */
        DocumentDetailOut: {
            /** Doc Id */
            doc_id: string;
            /** Source */
            source: string;
            /** Title */
            title: string;
            /** Subject */
            subject: string;
            /** Tags */
            tags: string[];
            /** Scope */
            scope: string;
            /** Chunks */
            chunks: components["schemas"]["ChunkOut"][];
        };
        /** DocumentList */
        DocumentList: {
            /** Documents */
            documents: components["schemas"]["DocumentSummaryOut"][];
        };
        /**
         * DocumentSummaryOut
         * @description One document row in the admin list — aggregated from its chunks.
         */
        DocumentSummaryOut: {
            /**
             * Doc Id
             * @description Stable identity (the ingest path/key).
             */
            doc_id: string;
            /**
             * Source
             * @description Where the document came from (e.g. filename).
             */
            source: string;
            /**
             * Title
             * @description Human display label (defaults to source).
             */
            title: string;
            /**
             * Subject
             * @description Single controlled grouping ('' when unset).
             */
            subject: string;
            /**
             * Tags
             * @description Free-form labels.
             */
            tags: string[];
            /**
             * Scope
             * @description Origin partition; 'global' for the shared corpus.
             */
            scope: string;
            /**
             * Chunk Count
             * @description How many chunks this document is stored as.
             */
            chunk_count: number;
            /**
             * Latest Ts
             * @description Newest chunk timestamp (last ingest).
             */
            latest_ts: string;
        };
        /** EditSubject */
        EditSubject: {
            /**
             * Name
             * @description New name (cascades to tagged docs).
             */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * EditTags
         * @description Add and/or remove free-form tags on a document.
         */
        EditTags: {
            /** Add */
            add?: string[];
            /** Remove */
            remove?: string[];
        };
        /** Fact */
        Fact: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /**
             * Ts
             * @default
             */
            ts: string;
        };
        /**
         * FactsResult
         * @description The facts after a write, plus the new version token to carry forward.
         */
        FactsResult: {
            /** Facts */
            facts: components["schemas"]["Fact"][];
            /** Version */
            version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestDocument
         * @description Add a document. The resolver (paste / upload) has already produced
         *     `(title, text)`; re-using an existing `doc_id` replaces that document.
         */
        IngestDocument: {
            /**
             * Title
             * @description Display title (and source).
             */
            title: string;
            /**
             * Text
             * @description The document's full text.
             */
            text: string;
            /**
             * Doc Id
             * @description Identity; derived from title if absent.
             */
            doc_id?: string | null;
            /**
             * Subject
             * @description Subject (must exist in the registry), or ''.
             * @default
             */
            subject: string;
            /** Tags */
            tags?: string[];
        };
        /** IngestResult */
        IngestResult: {
            /** Doc Id */
            doc_id: string;
            /** Chunks Indexed */
            chunks_indexed: number;
        };
        /** Persona */
        Persona: {
            /** Text */
            text: string;
        };
        /**
         * Profile
         * @description A user's durable memory: curated facts + any raw `remember` facts + episode
         *     bodies. `version` is the facts file's optimistic-concurrency token — echo it on
         *     a fact write or risk a 409.
         */
        Profile: {
            /** Facts */
            facts: components["schemas"]["Fact"][];
            /** Raw Long Term */
            raw_long_term: string[];
            /** Episodes */
            episodes: string[];
            /** Version */
            version: string;
        };
        /** PutRawFile */
        PutRawFile: {
            /**
             * Content
             * @description The full new file content (replaces the file).
             */
            content: string;
            /**
             * Expected Version
             * @description The version from the last read; rejected with 409 if stale.
             */
            expected_version?: string | null;
        };
        /**
         * RawFile
         * @description One memory file's raw content + its version token (optimistic concurrency).
         */
        RawFile: {
            /** Kind */
            kind: string;
            /** Content */
            content: string;
            /** Version */
            version: string;
        };
        /**
         * RenameDocument
         * @description Edit a document's display label. Identity (`doc_id`) is untouched.
         */
        RenameDocument: {
            /**
             * Title
             * @description The new display title.
             */
            title: string;
        };
        /**
         * SessionDetail
         * @description One session's machine-managed state, read-only.
         */
        SessionDetail: {
            /** Turns */
            turns: components["schemas"]["Turn"][];
            /** Summary */
            summary: string;
            /** Pending */
            pending: components["schemas"]["Turn"][];
        };
        /** SessionList */
        SessionList: {
            /** Sessions */
            sessions: string[];
        };
        /**
         * SetSubject
         * @description Assign a document's subject (the controlled grouping). '' clears it.
         */
        SetSubject: {
            /**
             * Subject
             * @description The subject name (from the registry), or '' to clear.
             */
            subject: string;
        };
        /** SubjectListOut */
        SubjectListOut: {
            /** Subjects */
            subjects: components["schemas"]["SubjectOut"][];
        };
        /** SubjectOut */
        SubjectOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** TagList */
        TagList: {
            /** Tags */
            tags: string[];
        };
        /** Turn */
        Turn: {
            /**
             * Role
             * @default
             */
            role: string;
            /**
             * Content
             * @default
             */
            content: string;
            /**
             * Ts
             * @default
             */
            ts: string;
        };
        /** UpdateFact */
        UpdateFact: {
            /**
             * Text
             * @description The fact's new text.
             */
            text: string;
            /** Expected Version */
            expected_version?: string | null;
        };
        /** UserList */
        UserList: {
            /** Users */
            users: components["schemas"]["UserSummary"][];
        };
        /**
         * UserSummary
         * @description One user row in the memory viewer.
         */
        UserSummary: {
            /** User Id */
            user_id: string;
            /** Fact Count */
            fact_count: number;
            /** Episode Count */
            episode_count: number;
            /** Session Count */
            session_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_documents_admin_v1_knowledge_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentList"];
                };
            };
        };
    };
    ingest_document_admin_v1_knowledge_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestDocument"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_admin_v1_knowledge_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagList"];
                };
            };
        };
    };
    set_document_subject_admin_v1_knowledge_documents__doc_id__subject_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSubject"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_document_tags_admin_v1_knowledge_documents__doc_id__tags_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditTags"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_admin_v1_knowledge_documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_admin_v1_knowledge_documents__doc_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_document_admin_v1_knowledge_documents__doc_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameDocument"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subjects_admin_v1_knowledge_subjects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectListOut"];
                };
            };
        };
    };
    create_subject_admin_v1_knowledge_subjects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubject"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subject_admin_v1_knowledge_subjects__subject_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_subject_admin_v1_knowledge_subjects__subject_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditSubject"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_admin_v1_memory_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
        };
    };
    get_profile_admin_v1_memory_users__user_id__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_fact_admin_v1_memory_users__user_id__facts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddFact"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactsResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_fact_admin_v1_memory_users__user_id__facts__fact_id__delete: {
        parameters: {
            query?: {
                expected_version?: string | null;
            };
            header?: never;
            path: {
                user_id: string;
                fact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactsResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_fact_admin_v1_memory_users__user_id__facts__fact_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                fact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFact"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactsResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_user_sessions_admin_v1_memory_users__user_id__sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_admin_v1_memory_users__user_id__sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_persona_admin_v1_memory_persona_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Persona"];
                };
            };
        };
    };
    get_raw_file_admin_v1_memory_files__kind__get: {
        parameters: {
            query?: {
                user_id?: string | null;
                session_id?: string | null;
            };
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RawFile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_raw_file_admin_v1_memory_files__kind__put: {
        parameters: {
            query?: {
                user_id?: string | null;
                session_id?: string | null;
            };
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutRawFile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RawFile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
